# Generated by Django 5.1.4 on 2025-01-12 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogpost_published_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='created_date',
            new_name='created_at',
        ),
    ]
